import type { ScheduleData } from "./types";

export const schedules: ScheduleData[] = [
  {
    regNo: "1234 A",
    soNumber: "A1B2C",
    companyId: "008",
    companyName: "Company A",
    marketingArea: "International",
    serviceType: "Full",
    pic: "Budi Santoso",
    scheduleAudit: "01 January 2023",
    totalPrice: "1.250.000",
    transportation: "Company",
    accommodation: "Company",
    scheduleType: "Open Date",
    status: "Ready to Schedule",
  },
  {
    regNo: "1234 B",
    soNumber: "A1B2C",
    companyId: "008",
    companyName: "Company A",
    marketingArea: "International",
    serviceType: "Mandiri",
    pic: "Siti Aminah",
    scheduleAudit: "02 February 2023",
    totalPrice: "3.750.000",
    transportation: "Company",
    accommodation: "Company",
    scheduleType: "Fix Date",
    status: "Accepted",
  },
  {
    regNo: "1234 B",
    soNumber: "A1B2C",
    companyId: "008",
    companyName: "Company A",
    marketingArea: "International",
    serviceType: "Mandiri",
    pic: "Siti Aminah",
    scheduleAudit: "02 February 2023",
    totalPrice: "3.750.000",
    transportation: "Company",
    accommodation: "Company",
    scheduleType: "Fix Date",
    status: "Accepted",
  },
  {
    regNo: "1234 B",
    soNumber: "A1B2C",
    companyId: "008",
    companyName: "Company A",
    marketingArea: "International",
    serviceType: "Mandiri",
    pic: "Siti Aminah",
    scheduleAudit: "02 February 2023",
    totalPrice: "3.750.000",
    transportation: "Company",
    accommodation: "Company",
    scheduleType: "Fix Date",
    status: "Accepted",
  },
];
